# do not touch this line
configVersion: 2

name: smart--office
description: >-
  Automate an office, you will be able to control room temperature and light
  using the smartphone. Another great feature is the ability to unlock the
  office door using facil recognition and on automaton mode, it will be able to
  turn all features off using the default distance between smartphone and
  matrix.
keywords: 'iot, face detection, smart, office'
displayName: Smart Office
categories:
  - entertainment
  - development
sensors:
  - temperature
services:
  faceTest:
    engine: detection
    type: face
