# do not touch this line
configVersion: 2

name: teste
description: gsa
keywords: ds
displayName: Teste
services:
  faceTest:
    engine: detection
    type: face
  faceDemo:
      engine: recognition
      type: face
  fistWatch:
    engine: gesture
    type: palm
